= Profiling and Extending the CIM with LinkML

Use cases may require extensions to the CIM, or simply the use of other vocabularies and schemas besides those from or based on the CIM. This can be achieved in a variety of ways, each of which having their own pros and cons. Most notably, modeling choices might impact compliance with the CIM standard.

In this document we will touch on:

* What it means to be compliant with the CIM standard, and what is required in order to achieve it.
* How to extend the CIM if what it provides does not suffice for a certain use case.
* How to choose between the various ways in which the CIM can be extended, discussing in particular the trade-off between semantic expressiveness and CIM compliance.

[NOTE]
--
This guide closely follows the <<CIM-PRIMER>> where applicable, but sets out to enhance it in two ways by:

* decoupling the modeling principles and guidelines from the practical instructions specific to Sparx EA and UML;
* providing practical instructions for using LinkML for how to do the profiling and extending.
--

== CIM compliance
"We need to conform to the standard."
-- Anyone

Plenty of people understand the importance of standardization, but what exactly is required in order be compliant is not always clear. This could either be due to a lacking level of formality of the standard, or due to people misunderstanding or not knowing how to conform.

.CIM data types
====





The CIM has defined custom data types ("CIM data types") which are modeled as classes in the official UML model. However, many vendors choose not to implement these data types as classes or some other compound structure, but represent them as simple primitives.

Is this deviating from the standard? It seems to be, but then again, some technical languages might not even be able to represent compound structures at all, in which case TODO
====

In the case of the

=== Semantic compliance

The ca




=== Structural compliance

The CIM comes with a set of profile groups, each of which consists of multiple profiles


== Profiling with LinkML

=== Creating a subset of the CIM

=== Adding constraints

=== Adding machine-readable semantics

==== Linked Data URI mappings

==== Term definition mappings

=== Using other vocabularies and schemas

== Extending the CIM

=== Adding new (sub)classes

=== Adding new attributes

=== Adding new relations

=== Further constraining

==== Enumerations

==== Code lists


[glossary]
== Glossary

[glossary]
[[dfn-contextual-model]]contextual model:: See: <<dfn-profile>>.

[[dfn-profile]](application) profile:: Subset of an <<dfn-information-model>> with application-specific constraints.
+
Also known as: <<dfn-contextual-model>>.

[[dfn-cim-profile]]CIM profile:: A <<dfn-profile,profile>> which is derived from the (full) canonical CIM.

[[dfn-information-model]]information model:: A technology-agnostic representation of concepts, relationships, constraints, rules and operations to specify data semantics for a chosen domain of discourse.

[[dfn-logical-data-model]]logical data model:: as

[bibliography]
== References
* [[[CIM-PRIMER]]] Common Information Model; Primer: Ninth Edition.; EPRI, Palo Alto, CA: 2023.; 3002026852.